### ISSUE TITLE
Maintenance tasks for finding sceners with dupe nicks / sceners matching group names

### ISSUE THREAD

**Issue by sagamusix** [demozoo/demozoo#120]
When trying to add T$ to some credits, I noticed that the drop-down menu there offered me T$/ATZ, another scener named T$ and a group named T$ (these dupes have since been removed, so they just serve as an example here). Since the normal search filters out non-alphabetic characters, a search for "T$" yields way too many wrong results to be able to find those bogus profiles. While I understand that finetuning and fixing the search is probably a larger task, it would probably make sense to have maintenance tasks for finding sceners with duplicate nicks, or sceners whose nicks match demogroup names.

**Comment by glennlunder** [comment]
For one this issue is now 5 years old, and for two we've replaced our entire search functionality since then, and for three three there are now a number of maintenance reports dealing with de-duping duplicate names of various kinds, so I would prefer if there is still issues here we open more specific issues.

**Comment by sagamusix** [comment]
We have indeed replaced the search and things just got worse in this specific example because now you cannot search for T$ at all anymore... ;)

**Comment by nswaldman** [comment]
@sagamusix could you like to an appropriate ticket? At a glance it doesn't seem to be reported.

**Comment by sagamusix** [comment]
I think I talked to Gasman about this after the new search was 
introduced and the verdict was that one can still search for "TS" and 
that no exceptions for certain punctuation or other special characters 
would be added.

**Comment by gasman** [comment]
That's not quite how I remember it, and we did in fact put in a special case for T$ (https://github.com/demozoo/demozoo/commit/1b619ac090968a667a51faec3cf495f692533774) :-) It's possible that it only works for SQL-based searches (e.g. the auto-suggest dropdown) rather than the main search view, though.

Either way, if there are problems still remaining with searching for T$, it's worth us having an issue open to document that - it may be that it's prohibitively hard to make it work on the main search, but better to have a (low-priority) ticket documenting that fact rather than letting it be forgotten.

**Comment by sagamusix** [comment]
The replacement does seem to work for the auto-suggest results, however 
the exact match doesn't seem to be relevant enough to actually show up 
in the popup, so tons of other results containing "TS" show up instead.
