### ISSUE TITLE
Production / credit count on scener page

### ISSUE THREAD

**Issue by gundelsby** [demozoo/demozoo#152]
Either at the top of the page or in the header for the relevant category heading.

**Comment by DannyCork** [comment]
Sounds like a good addition, something like this?

![cred](https://cloud.githubusercontent.com/assets/3512672/13667151/f989a80e-e6ac-11e5-8a7b-1e1d5f4a05fe.png)

Should the # of prods would be a hypelink to the list of productions?

**Comment by glennlunder** [comment]
TBH I think that implementation looks a lot less clean with the text between the various nicks and the location - I actually think the single number after Productions would be perfectly enough.

As for a hyperlink to the productions, I don't see the need for that - since they are all on that page anyway?

**Comment by gasman** [comment]
Implemented in #574.
