### ISSUE TITLE
Support Spotify links for songs

### ISSUE THREAD

**Issue by glennlunder** [demozoo/demozoo#158]
More and more demosceners are putting their music on Spotify (and other streaming services). I noticed while adding a link for Response's soundtack to The Wizard of Cos, that we don't support those links in that they don't show up with a nice shiny Spotify logo. We should support that. :)

Example: http://demozoo.org/music/133367/

I'm sure there is more.

**Comment by gasman** [comment]
We do recognise Spotify links, but only the formats http://open.spotify.com/artist/1RZWDWwVCfHBSM4grwmlix for artists and https://play.spotify.com/track/5ldB9y5idb2ZczRsGaRWmk (NB play.spotify.com, not open.spotify.com) for tracks. I closed my Spotify account due to general spamminess, so I can't check these links for myself - so a few questions:

* Are open.spotify.com and play.spotify.com interchangeable? (i.e. do https://play.spotify.com/track/5ldB9y5idb2ZczRsGaRWmk and http://open.spotify.com/track/5ldB9y5idb2ZczRsGaRWmk refer to the same track, and likewise http://open.spotify.com/artist/1RZWDWwVCfHBSM4grwmlix and https://play.spotify.com/artist/1RZWDWwVCfHBSM4grwmlix ?)
* Is there any reason to prefer one of those URLs over the other, when we display the link? (e.g. does Spotify redirect you from one domain to the other, or does one version of the page have more useful information on it?)
* What about http versus https? Does https work on both domains? Does it redirect you from http to https?

**Comment by glennlunder** [comment]
I can confirm all your example open.-urls lead to play.-urls here, and they
all forward to https.
