### ISSUE TITLE
HTML lists in prod "blurb" don't like newlines

### ISSUE THREAD

**Issue by sagamusix** [demozoo/demozoo#161]
When using a HTML list in a prod description, like this:
```
<ul>
<li>First item</li>
<li>Second item</li>
</ul>
```
Then newlines (`<br>`) are inserted after every line, which generates ugly empty lines and invalid HTML code. It's really just a minor issue since you can stuff everything into a single code line, but still annoying.

**Comment by gasman** [comment]
This is a feature, not a bug :-) The notes field is 'officially' Markdown, not HTML, so use the Markdown list format (`*` before each item) and you'll be fine...

We use Markdown because it has the nice feature that it gets out of your way if you don't want to use it - you can just write plain text, and don't have to use `<p>` tags for line breaks, or escape `<` and `&` characters. It will also accept some simple HTML markup - and for some reason, people here like to use that a lot :-) - but to achieve this flexibility, it has to take some "artistic licence" with its use of line breaks, and that's what you're seeing here.

**Comment by sagamusix** [comment]
Ah, fancy. :) Maybe this should be made more clear in a visible place, e.g. directly under the edit boxes?
