### ISSUE TITLE
Remove Push'n'Pop links

### ISSUE THREAD

**Issue by glennlunder** [demozoo/demozoo#203]
...since the site died a horrible death in a ball of flames and destruction and general mayhem.

No, but seriously - they were very clear there were no backups and they were not coming back, so let's just get rid of all those links. It's not very useful to have links leading to nowhere, unfortunately.

Alternatively, plan b, we could divert them to a generic waybackmachine url?

Thoughts welcome, but either way something needs to be done.

**Comment by DannyCork** [comment]
What is/was Push'n'Pop?

**Comment by glennlunder** [comment]
Push'n'Pop was an Amstrad CPC demoscene site, that suffered a fatal hardware crash and signalled that they would not be coming back.

**Comment by DannyCork** [comment]
Thanks for that info Glenn.
So what to do ? Create and run a maintenance report which identifies these links and removes them?

**Comment by gasman** [comment]
My plan is to come up with a system of 'archiving' external links so that they're still in the database but aren't visible or editable. That way, we can also deal with zxdemo.org links neatly too (zxdemo.org is effectively a Spectrum-only mirror of Demozoo now, so there's no need for anyone to edit those links any more).

**Comment by glennlunder** [comment]
I just noticed a link where push'n'pop hosted a download too, so we should probably also be looking for links in our downloads.

Example in question: http://pushnpop.net/Download/Demos/CPC%20in%20Wonderland%20(Electro).zip
