### ISSUE TITLE
Link for slengpung does not show on the profile

### ISSUE THREAD

**Issue by Creonix** [demozoo/demozoo#213]
**as in topic

1- add link for slengpung for the scener or a group
2- save it
3- as other links show the slengpung does not.**

**Comment by gasman** [comment]
Hi @Creonix,
This is done intentionally for Slengpung links, since many sceners don't want their demoscene work to be linked to their real-world identities - as we don't know what each scener's stance on this is, we err on the side of caution and omit these links from the main profile page. In future we intend to add a mechanism where users can "opt in" to displaying their own Slengpung link.

**Comment by Creonix** [comment]
Ok aknowledged! Thx
