### ISSUE TITLE
Allow music to have associated art/screenshot

### ISSUE THREAD

**Issue by glennlunder** [demozoo/demozoo#215]
Ties into #207 I guess, and has also been requested directly to me over twitter by Asbjørn Ulsberg.

The concept is to allow "screenshots" for music, which in turn can be used as a background for the player - much in the way it is now in fact, except we're using a generic waveform.

There are several instances where it would make sense to allow this - for instance C64 music compo entries often come in the form of executable files with some sort of visual element to them - whether that be text, or a logo, or even a full picture presentation. Lots of sceners (just off the top of my head: DaneBD) also release their tunes on Spotify and other places, where they include specific artwork which serves as the cover art for that tune.

Plus, it would look good, which is not a reason without merit either. :)

**Comment by asbjornu** [comment]
I reported my wish as #212. I would love to see this implemented! ❤️

**Comment by glennlunder** [comment]
@asbjornu #212 is "Add player support for Soundcloud"... which is not quite the same thing :)

**Comment by glennlunder** [comment]
Afterthought: We may want to relabel "screenshot" to "artwork" when someone wants to submit an image for a music piece.

**Comment by asbjornu** [comment]
@glennlunder True! "Artwork" is what most music software calls that sort of visual metadata, so: 👍

**Comment by Creonix** [comment]
i support the thread as I always ve seen my music entries plain without a screenshot.
But I have maybe better suggestion, to make the music files standarised f.e. MOD and tracked music will have one screenshot (for all), exe music another one, etc

**Comment by glennlunder** [comment]
Ehm, did we sneakily implement that, or is this some kind of mistake?

![image](https://user-images.githubusercontent.com/2839057/28036176-a4f06f5e-65b7-11e7-9dd8-cbf4057e53c7.png)

**Comment by gasman** [comment]
It was a mistake (of the really mundane "missed out a couple of brackets at a crucial point in the code" variety). But I suppose you're not just going to let me fix that now, are you...? ;-)

So I guess what we're calling for here is to allow screenshots on music (i.e. rip out all the lovingly-crafted logic that says "don't show the screenshot button if this is music" :-) ), with the difference that:

* any text that mentions "screenshots" (namely: the "Add screenshot" / "Manage screenshots" / "All screenshots" buttons, the "Add a screenshot" item in the "Add other information" dropdown, the "Upload a screenshot" popup and the "Manage screenshots" / "All screenshots" sub-pages) should say "artwork" instead. (I suggest we _don't_ try to make an exception for C64 music etc, where it's likely to actually be a screenshot - that's just complicating things...)
* Artwork will be used as the background to the Cowbell music player, in place of the fake waveform image
* The "Add artwork" button for music will not get Special Carousel Bumping Privileges. (For graphics and executables, whenever the prod has no screenshots or video to show in the carousel, the "Add screenshot" button is dropped in favour of showing the "No screenshot yet! Add one" notice in the carousel area. This *won't* happen for "Add artwork" on music: the button will stay, and the carousel area will just show the turntable icon. This is because not all tracks have artwork: missing artwork is not a 'failure' condition, and it seems wrong to have a call-to-action for something that might not exist)
* the "prods without screenshots" maintenance report will continue to ignore music.

**Comment by glennlunder** [comment]
Yes, yes, yes and yes! :D

**Comment by gasman** [comment]
Mostly implemented in 8b68b3d5e87b14ddb51550646ec468feae61c85f / 5bcd0addf019f994ff6630d0664bf96ea1449871 - remaining task is to use the artwork as the background for Cowbell, which I'll hopefully get done tonight.

**Comment by gasman** [comment]
Completed in ac98ace1a54b9ee1964dc29ddc05df1f80367404.

Example of it in action (it's kind of hard to find a track that's both Cowbell-playable and has something suitable to use as artwork, though :-) ): https://demozoo.org/music/15738/

**Comment by asbjornu** [comment]
[Looking good](https://demozoo.org/music/160488/)! 😄 👍
