### ISSUE TITLE
Markdown list formatting does not look very nice in platform descriptions

### ISSUE THREAD

**Issue by sagamusix** [demozoo/demozoo#218]
Long story short: https://demozoo.org/platforms/71/
There are a couple of markdown lists in that article, but they are not recognizable as such due to some CSS that should probably not be applied here.

**Comment by gasman** [comment]
Platform descriptions are only meant to be a paragraph or two (and markdown is only really enabled so that you can include links). If you want to write a long-form article about the platform, I suggest you create that as a standalone page (https://demozoo.org/admin/pages/page/) and link to that from the description.
