### ISSUE TITLE
Production assigned to two different nicknames of same scener should only show up once in their profile

### ISSUE THREAD

**Issue by sagamusix** [demozoo/demozoo#219]
Some of [rayn](https://demozoo.org/sceners/3693/)'s prods are credited to both nicknames "ptrance" and "rayn". As a result, they also show up twice in the production list. They really should only show up once there.

**Comment by gasman** [comment]
Fixed in cc562e1143cfa605cf8c33bbb3a28052b151ff8c. Note that this doesn't eliminate the duplicates when the author is listed multiple times in the _credits_ of a prod, rather than as the overall author - in this case, the multiple entries are legitimate, because they correspond to meaningfully distinct database records (for example, it's possible for one "persona" to be credited for music, and another for graphics).
