### ISSUE TITLE
Production assigned to two groups where one is a subgroup, should not be listed twice

### ISSUE THREAD

**Issue by glennlunder** [demozoo/demozoo#221]
This is the same problem as #219, just in the context of groups. Example: Virtual Dreams is a subgroup of Fairlight, and hence productions like [History Line](https://demozoo.org/productions/26282/) are listed twice on the Fairlight profile.

**Comment by gasman** [comment]
I think this behaviour is legitimate. History Line appears on both the "Productions" and "Member Productions" lists, because it has a byline of "Virtual Dreams and Fairlight" - this technically makes it both a production of Fairlight, and a production of a member (subgroup) of Fairlight. I can't see any good logical basis for it _not_ to be on both lists :-)
