### ISSUE TITLE
sceneId authentication redirects to main page, not page user was on

### ISSUE THREAD

**Issue by DannyCork** [demozoo/demozoo#242]
So I'm on this page https://demozoo.org/productions/93374/ and I want to add a credit, so I click on edit credit. Unfortunately I'm logged out so I'm then presented with a login page https://demozoo.org/account/login/?next=/productions/93374/ *nb: ?next= contains the return url.
I then click on scene id and authenticate and am dumped back at http://www,demozoo.org and not at the original page I was on.

 Scene.org redirect_url parameter docs https://id.scene.org/docs/

**broken flow is:**
- https://demozoo.org/productions/93374/
- https://demozoo.org/account/login/?next=/productions/93374
- https://id.scene.org/oauth/authorize/?state=xxxxx&redirect_uri=https%3A%2F%2Fdemozoo.org%2Faccount%2Fsceneid%2Flogin%2F&response_type=code&client_id=demozoo **redirect_url param doesn't point to where we came from**
- http://demozoo.org **(should be https://demozoo.org/productions/93374/)**

**Comment by gasman** [comment]
I tried to make this work when I merged in the SceneID support, but wasn't able to do so due to a limitation at the scene.org end. To get the 'next' parameter to survive the round-trip to scene.org and back, you'd have to pass it as part of the `redirect_uri` parameter, which would be a URL of the form `/account/sceneid/login/?next=/productions/93374/`. However, the SceneID server is apparently configured to only accept the exact URL `/account/sceneid/login/`. (Which would seem to undermine the point of it being a parameter, really :-) )

Gargaj has suggested that we should stash the 'next' parameter in the session instead, rather than passing it in the URL.

**Comment by Gargaj** [comment]
I can whip this up over the weekend 'cos it annoys me.

**Comment by Gargaj** [comment]
There we go.

**Comment by DannyCork** [comment]
epic !

**Comment by gasman** [comment]
Fixed in #358
