### ISSUE TITLE
scenesp.org mirror downloads from scene.org not properly recognized

### ISSUE THREAD

**Issue by glennlunder** [demozoo/demozoo#258]
Example url: https://files.scene.org/get/mirrors/scenesp.org/diskmags/trashcan/trashcan1-1.dms

This does not get recognized as a scene.org mirror download, and hence the appropriate mirror downloads do not appear.

**Comment by gasman** [comment]
I don't think this is anything to do with it being a scenesp.org mirror link - it's because you've used the files.scene.org/get redirect URL as the download URL, which we don't currently recognise. If you use any other kind of link (such as the URL of the 'view' page, or a direct FTP link) you'll get the expected behaviour.

**Comment by glennlunder** [comment]
I see. So it's a twofold issue then;

a) We probably need to recognize all variant urls from scene.org, including "get" ones. I got the link from a different source, and it is valid, so it's highly probable more of these will get pasted into the database in the future.

b) Can we do a quick search-and-replace to make all the existing ones valid? I added a few ones today, there is probably others.

**Comment by gasman** [comment]
b) is no problem - whenever we add a new recognised link format, we always run through the database to catch any existing links that need converting.
