### ISSUE TITLE
Competitions admin panel - possibility to search

### ISSUE THREAD

**Issue by glennlunder** [demozoo/demozoo#259]
In the admin panel for competitions - https://demozoo.org/admin/parties/competition/ (available only to admins, sorry random user :P), it would be super helpful to be able to search like we can in a number of the other admin panels. This would be a huge timesaver when looking for a competition to delete for instance - if I could just search for "TRSAC 2016 Graphics", then I would get to where I want to go a hell of a lot quicker.

**Comment by gasman** [comment]
This probably isn't entirely straightforward, since there's no database field with the exact text "TRSAC 2016 Graphics" that we can search on - that title is made up of two separate records, the party ("TRSAC 2016") and the compo ("Graphics"). Could probably be done with some custom logic that splits the search term by word and searches each one individually, though.

**Comment by glennlunder** [comment]
Just the ability to search for "trsac 2016" alone would help heaps!

**Comment by sagamusix** [comment]
*bump* the same would be super useful to have for most other pages, such as the list of existing tag descriptions.
