### ISSUE TITLE
prods: Request new info field for scrolltext

### ISSUE THREAD

**Issue by cxw42** [demozoo/demozoo#284]
Could we have a new "Add other information" field for text within a prod?  E.g., scrolltext, greetz, whatever people want to capture for posterity?  I just watched [Full Moon](https://demozoo.org/productions/5783/) and you can only catch half of the text at the end on the first watch.  Similarly, [Crystal Dream II](https://demozoo.org/productions/175/) actually says "Danger do not try to read this text" if I recall correctly :) .

This is something individual users could add and I don't think it would require moderator attention.  Having a centralized place for the text would make it easier to find than in the comments.  Also, long texts in a dedicated field could be shown in a sub-page rather than in the main page for the prod, as infos are on Pouet presently.

The code for this could be reused for NFO/DIZ files, or those could be handled separately.  This request would benefit from #47, but doesn't require it.

**Comment by DannyCork** [comment]
An excellent suggestion

**Comment by glennlunder** [comment]
Actually, I'm gonna have to be bad cop on this one. We talked at length when we established Demozoo about "the right amount of information", and how it's easy to go overboard. We used the extraction of scrolltext and the listing of groups that get greeted - both from Janeway - as examples of going overboard in those talks. That information is easily available from partner sites that we link out to, as the aforementioned Janeway, and there is nothing stopping people from dropping text on paste services and linking to those.

I much prefer our current editorial line of extracting the actual relevant information and presenting that as part of a narrative, rather than impenetrable amounts of scrolltexts that would add clutter to our ui.
