### ISSUE TITLE
Update RECOIL to 4.0.0

### ISSUE THREAD

**Issue by glennlunder** [demozoo/demozoo#297]
RECOIL 4.0.0 (2017-05-17)

Formats:

Atari 8-bit: added Graph2Font (G2F), GED, Floor Designer (FGE), Standard Graphics 3 (SG3), Graphic Arts Department (PIC), Texture Maker0 16x16x16 (TX0), DrawIt, Sketch-PadDles (SKP), improved MCH
Atari ST/TT/Falcon: added dozens of formats and improved the existing ones, thanks to Lonny Pursell
Amiga: slightly improved IFF
ZX81: added ZXpaintyONE (ZP1, RAW), fixed P
Ports:

Windows thumbnails: enable thumbnails automatically in folders with images
RECOILWin: support high-resolution displays
Windows 10: improved icons, display filename
recoil2png: process next files after an error
Android: switched to the standard build system

**Comment by DannyCork** [comment]
Recoil now on RECOIL 4.3.1 (2018-12-05)

**Comment by gasman** [comment]
Updated to RECOIL 5.0.0 / pyrecoil 0.3.0 in 5e409dabf822714b8ec7964d47d1f6df6348efc8. Note that I _haven't_ added any of the newly-supported image formats to our recognised list at https://github.com/demozoo/demozoo/blob/master/screenshots/models.py#L14-L23 , because we have to balance the probability of someone actually trying to upload a file of that type, against the probability of a false match for a particular file extension when we process the contents of a .zip file for a graphics entry.

If there's a [RECOIL-supported format](http://recoil.sourceforge.net/formats.html) not on [this list](https://github.com/demozoo/demozoo/blob/master/screenshots/models.py#L14-L23) that you're particularly keen for us to recognise, let me know!
