### ISSUE TITLE
Wrong auto-correction for scene.org link

### ISSUE THREAD

**Issue by sagamusix** [demozoo/demozoo#314]
Not sure if this can be fixed easily.
The following scene.org link was spread: https://files.scene.org/browse/parties/2017/riverwash17
Note the absence of a slash at the end.
Trying to add it as a party link on Demozoo auto-corrects it to https://files.scene.org/browse/parties/2017/ instead of https://files.scene.org/browse/parties/2017/riverwash17/

**Comment by gasman** [comment]
Fixed in 182bdf8ac53ad2b21187621979329e5def5c1ec5. This will match a scene.org (or Fujiology) link with or without a trailing slash, in the specific contexts where we're expecting a folder rather than an individual file - namely releaser and party links - and add the trailing slash if it isn't present.

This _does_ mean that if for some crazy reason someone adds a specific file from scene.org / Fujiology as an external link for a party or releaser, we'll wrongly assume that it's meant to be a folder and silently break the link by adding a trailing slash. But I think that's a necessary evil to make the more likely scenarios work...
