### ISSUE TITLE
Productions Without Screenshots not properly picking out images that DOES have screenshots

### ISSUE THREAD

**Issue by glennlunder** [demozoo/demozoo#335]
Running this maintenance report specifically against Graphics - https://demozoo.org/maintenance/prods_without_screenshots?production_type=23 - still has Graphics entries in the list that DO have screenshots present - but seemingly not thumbnails. That may be why they're not getting picked up.

Two examples;

https://demozoo.org/graphics/19648/
https://demozoo.org/graphics/19561/

**Comment by gasman** [comment]
What do you mean by "screenshots, but seemingly not thumbnails"? I can't see anything unusual about the two entries you mention, on either the prod page or the party results listing. (If you're referring to how they appear on the prods-without-screenshots report itself, we don't bother loading thumbnails there, because obviously if things are working properly, there will never be any... :-) )

**Comment by gasman** [comment]
OK, hopefully fixed... There's a `has_screenshot` flag on the production model, which _should_ always be kept in sync with the presence or absence of screenshots, but for some reason these still had it set to false despite having screenshots. We did have a sanity check to spot and fix these cases, but it was disabled due to taking too long. I've now optimised and reinstated this check (although it still isn't running on any regular schedule).

That doesn't explain how the inconsistency happened in the first place, though... I think I've found (and fixed) one possible scenario where it could occur, involving one screenshot being deleted at the same time another one is being processed, but looking at the edit history it doesn't seem to match what happened here. Either way, all we can do now is wait to see if this recurs.
