### ISSUE TITLE
Edit button for credits disappears

### ISSUE THREAD

**Issue by glennlunder** [demozoo/demozoo#368]
The Edit button that appears next to credits, has recently disappeared after I add a credit, and will only reappear after I reload the page. Cleraring caches does not fix the issue. After a question in the Slack channel, @jensadne confirmed he was seeing the same.

This issue appeared recently, in the 1-2 weeks span, around the time we implemented edit locking for productions, so I have a sneaking feeling it's related.

Setup here: Chrome 64 bit 71.0.3578.98 on Windows 10.

**Comment by gasman** [comment]
I think this is happening because we're failing to pass the `prompt_to_edit` flag to the template [when re-rendering the credits block after an edit](https://github.com/demozoo/demozoo/blob/f890665769b2311f4b31f82dea76f7d31923fb7b/productions/views/productions.py#L973), as we do [when rendering the overall page](https://github.com/demozoo/demozoo/blob/f890665769b2311f4b31f82dea76f7d31923fb7b/productions/views/productions.py#L132).
