### ISSUE TITLE
Automatically translate URLs when entering soundtracks / credits

### ISSUE THREAD

**Issue by sagamusix** [demozoo/demozoo#375]
Today I had to delete a music entry whose title was essentially `https://demozoo.org/music/some-id/` - clearly someone tried to attach an existing music entry to a demo and thought they could do so by pasting an URL. And actually that is a pretty neat idea. We should accept URLs when entering soundtrack details, credits for a demo, or pack contents, and they should automatically convert into the correct music / scener / prod item accordingly.

**Comment by sagamusix** [comment]
This would also be really helpful when trying to assign a soundtrack/credit with an incredibly common name, since the number of suggestions is limited (soundtrack) or picking the correct scener profile may be impossible with the information you get from the dropdown (e.g. several artists with no group affiliations and from the same country or no country specified)

**Comment by sagamusix** [comment]
Another place where this would come in really handy are compo results when matching entries that are already in the database, for example when removing dupes and the song name is a really common prefix of other prod names.

**Comment by sagamusix** [comment]
Apparently another place where this would be helpful is adding BBStros to BBSes, because there are quite a few of these simply named "BBStro" in the database.

**Comment by pebroz** [comment]
Either entering URLs or IDs would help getting the exact match you want when submitting data.

**Comment by gasman** [comment]
Implemented for production lookups in #595. I had a go at the same thing for nick lookups in #596, but it got messy, because the nick field code is pretty complicated (partly because there's a lot for it to deal with, partly because I wasn't as familiar with Django tricks when I wrote it, and partly because I insisted on making it usable without Javascript, which in retrospect was a whole lot of misplaced effort). I suspect that the prod lookup was 90% of what people wanted here, so I'll close this and open a new low-priority ticket for nick lookups (which I'll upgrade to normal-priority if it keeps coming up as a feature request).
