### ISSUE TITLE
BBS section enhancement: External links

### ISSUE THREAD

**Issue by glennlunder** [demozoo/demozoo#441]
It would be very useful to have external links support, for linking out to other sites and databases that have information on bbs'es. From the outset, there are four sites that we'd like "support" for in addition to normal external www links;

- Janeway. Here the bbs entity is treated as "authors" in the same way a group or a person is in the database. URL's in the format http://janeway.exotica.org.uk/author.php?id=62380 (example). Since we already have a dump of that database, it would be amazing if our first order of business could be importing that data so we avoid using time on things that are already in - and the external links come in as a bonus there.

- Pouët. URL's are in the format https://www.pouet.net/boards.php?which=3860 - and @gasman has mentioned an api for these are in the works.

- CSDb. URL's in the format https://csdb.dk/bbs/?id=2184

- BBSMates. URL's in the format http://www.bbsmates.com/viewbbs.aspx?id=122400 (mentioned by dipswitch)

**Comment by m100bit** [comment]
Since Defacto2 is supported now, we shouldn't forget that this website collects info about BBSes too. They are marked as groups, so URL's in the format https://defacto2.net/g/starport-bbs , the same as groups format.

There's also "Telnet BBS Guide" website that has some telnet BBSes, obviously. URL's in the format https://www.telnetbbsguide.com/bbs/vortex-bbs/
