### ISSUE TITLE
Support for Digital Symphony tunes

### ISSUE THREAD

**Issue by glennlunder** [demozoo/demozoo#465]
Once we upgrade https://github.com/demozoo/cowbell with a newer version of https://github.com/OpenMPT/openmpt, they recently added support for the Digital Symphony tracker format - which we also recently introduced on Demozoo. Hence, adding playability to files with the .dsym suffix would make these playable on Demozoo.

**Comment by sagamusix** [comment]
Note that there is no stable version supporting this format yet (it would have to be compiled from trunk), and this update would also bring support for SymMOD files (plus two other formats probably not used in demoscene context).

**Comment by gasman** [comment]
Implemented in dd1c8325ea5567224f697f355a40a78b31ca4910 - file on Modland with extensions .dsym, .symmod and .fmt (case insensitive) are now recognised as playable with libopenmpt. (Files on ModArchive in those formats were already being served through the player, since the URLs don't give us the file extension - the difference is that they now actually work in Cowbell 0.5.1 :-) )
