### ISSUE TITLE
ASCII / ANSI rendering through Ansilove

### ISSUE THREAD

**Issue by glennlunder** [demozoo/demozoo#47]
We need a way to render ascii and ansi files for web use, in order to accurately display various text files associated with productions (results, .nfo's), ascii and ansi collections, and file_id.diz'es etc.

We will probably implement Ansilove ( http://ansilove.sourceforge.net ) for this purpose, but it also brings up an issue of how to incorporate these features into the overall design (there would need to be things to click on to show nfo's for a prod, for instance).

We probably do still want to show them in the usual screenshot panel, and have them open up in a lightbox - but they should be shown in full resolution, with a scrollbar.

Ticket originally opened by gasman 2011-05-24, and content by myself and gasman.

**Comment by gasman** [comment]
Now under way at https://github.com/demozoo/demozoo/tree/ansilove!

So far I've built a management task to identify download links that are potentially renderable as ANSIs, similar to the one we have for grabbing screenshots of graphics prods (although this one currently isn't set up to run on a schedule, and doesn't yet look inside zip files). These are then mirrored at media.demozoo.org, with the appropriate HTTP headers so that we can fetch them from Javascript.

I've decided to go with client-side rendering using ansilove.js, as that gives us more flexibility to play with things like font variations and splitting extra-long ANSIs into a multi-column view. As of https://github.com/demozoo/demozoo/commit/3a5140c8c4e01c6fa1966fe7c265f0de1b41e161 the rendering is now fundamentally working, but doesn't scroll or zoom yet.

Having reached this point, I've now realised that we're probably going to need server-side rendering after all - because we need to have a suitable image to click on in the carousel (and really don't want to depend on Javascript rendering at that point). Luckily that's not an immediate problem, because the vast majority of ANSIs already have manually-created screenshots, thanks to our awesome site admins :-)

**Comment by glennlunder** [comment]
I'm assuming, based on "gives us more flexibility to play with things like font variations and splitting extra-long ANSIs into a multi-column view" that we're considering implementing that in a way so that also existing ansi renders (i.e. png's uploaded after being rendered offline) will receive the same treatment and get a special view method that allows scrolling and such?

**Comment by gasman** [comment]
Yep, that's correct. For any ASCII/ANSIs where we have the original file available, the lightbox popup will use the scrollable ansilove.js rendering, in preference to displaying the screenshot.

(...in fact, due to the thing I mentioned in my last paragraph above, _only_ the prods with manually-created screenshots will receive this treatment, at first. The carousel itself will still remain image-only - so until I've got the stuff in place to generate images automatically, we'll still be relying on users to create them.)

**Comment by bengarrett** [comment]
Hi guys here are [Viler](http://int10h.org/oldschool-pc-fonts/)'s _vga8_ and _vga9_ fonts. The originals are TrueType but I have added `woff` and `woff2` that significantly reduce the download size. They're released under a [CC sa-by](https://creativecommons.org/licenses/by-sa/4.0/) and required attribution to him if used.

[fonts-vga.zip](https://github.com/demozoo/demozoo/files/629901/fonts-vga.zip)

The vga8 and vga9 are close to identical, except that vga9 introduces 1px spacing between characters and a few glyph modifications to make the text more legible. vga8 is probably best suited for ascii art that uses block or box characters.

```html
<!DOCTYPE HTML>
<html>
<head>
	<style>
	@font-face {
	  font-family: font-vga-nine;
	  src: url('fonts-vga/pxplus_ibm_vga9.woff2') format('woff2'), 
	  url('fonts-vga/pxplus_ibm_vga9.woff') format('woff'), 
	  url('fonts-vga/pxplus_ibm_vga9.ttf') format('truetype');
	  font-display: swap;
	}
	@font-face {
	  font-family: font-vga-eight;
	  src: url('fonts-vga/pxplus_ibm_vga8.woff2') format('woff2'), 
	  url('fonts-vga/pxplus_ibm_vga8.woff') format('woff'), 
	  url('fonts-vga/pxplus_ibm_vga8.ttf') format('truetype');
	  font-display: swap;
	}

	.text-canvas {
	  padding: 0;
	  margin: 0;
	  background-color: black;
	  color: white;
	  /* color: #aaa for ms-dos grey */
	  /* normalise for the raster-like font */
	  font-size: initial;
	  font-style: normal;
	  font-weight: normal;
	  line-height: 1;
	  /* use pre formatting, except most text will be wrapped at 80 columns */
	  white-space: pre-wrap;
	}
	
	#example1 {
	  font-family: font-vga-eight;
	  width: 640px;
	  max-width: 640px;
	}
	
	#example2 {
	  font-family: font-vga-nine;
	  width: 720px;
	  max-width: 720px;
	}
	</style>
</head>
<body>
<pre class="text-canvas" id="example1">hello
world

	0 -> 80
01234567890123456789012345678901234567890123456789012345678901234567890123456789

	0 -> 120 (this won't wrap)
012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789

	0 -> 120 (this will wrap)
0123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789
</pre>
<br>
<pre class="text-canvas" id="example2">hello
world

	0 -> 80
01234567890123456789012345678901234567890123456789012345678901234567890123456789

	0 -> 120 (this won't wrap)
012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789

	0 -> 120 (this will wrap)
0123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789
</pre>
</body>
</html>
```

**Comment by gasman** [comment]
It seems to me that there are four separate tasks wrapped up in this ticket (and I'm not sure which of them are really considered 'highest-priority')...

1. Making ASCII/ANSI prods viewable. **Now completed** in 66057f3d50a4f98b86a70ed334048488c028204c (which adds Ansilove-C support to our screenshot processing, allowing ASCII/ANSI file formats to be accepted like any other image type) along with the other recent work to allow zooming/scrolling of screenshots.

(In the end I changed my mind about using ansilove.js, since A: we need server-side rendering anyway to generate thumbnails and images for the carousel, and B: it would have been silly to implement a zooming/scrolling interface specifically for ANSIs when we could get a lot more benefit from building those features into the general-purpose image viewer instead. We _could_ still adopt ansilove.js as a future development, using it in the lightbox while the carousel/thumbnails still use images - and that would give us the ability to adjust fonts and background colours on-the-fly - but IMHO that's a fairly marginal benefit at this point.)

2. Collecting .nfo files for prods (either accepting user uploads, or extracting them from downloads, or both)

3. Rendering those .nfo files, and the party results.txt files we already collect, in plain text using a nicer font than the current one ([example](https://demozoo.org/parties/708/results_file/207/)).

4. Rendering ANSI-based .nfo files, which are pretty rare but apparently do exist. Since these contain actual text information that we might want to copy/paste and index, we'd ideally hope do this as a text/HTML based rendering rather than canvas or image. (Does any code for this currently exist?) I think this is the absolute lowest priority, though.

**Comment by glennlunder** [comment]
I would consider .nfo rendering, and the ability for both us and users to submit new entries, to be priority number one.

So, points *2* and *3* would be my answer.

Point 1 we _CAN_ conceivably work around with local rendering and uploading png's, for the time being, even if it's a good bit of extra manual work.

So, should we split this ticket up into individual ones for each task?

**Comment by bengarrett** [comment]
For the least prioritised option __4__ I have an [ECMA-48 / ANSI.SYS to HTML BuildEcma48()](https://github.com/bengarrett/RetroTxt/blob/master/text_ecma48.js) function in ES6 JS. It doesn't have the same accuracy as ansilove due to a lack of support for backwards and up cursor positioning that was common in BBS era ANSI art. Its other issue is dealing with newlines; some docs expect the rendering to lock at 80 columns or higher. Others use ASCII C0 linefeed controls (the same as ASCII text), and some use the cursor control. The problem is sometimes docs combine these, and the parser has to guess, though I have seen ansilove fail with renderings too.

[javascript](https://github.com/bengarrett/RetroTxt/blob/master/text_ecma48.js)
[css dependancy 1](https://github.com/bengarrett/RetroTxt/blob/master/css/text_ecma_48.css)
[css dependancy 2](https://github.com/bengarrett/RetroTxt/blob/master/css/text_colors_vga.css)
