### ISSUE TITLE
BBSs as database entries

### ISSUE THREAD

**Issue by dipswitch-** [demozoo/demozoo#48]
I think it would be a good idea to enhance our database by including boards as entries. Boards have always been an important part of the different scenes up to the second half of the 1990s, many demosceners have been (co-)sysops, most demogroups had BBS affils, many coded BBS intros etc.

I have been setting up a BBS database within pouet some five-six years ago when PS was so kind to code the infrastructure for it: http://www.pouet.net/boards.php -- however, with Demozoo this could become much more amazing.

I propose the following content categories for within a BBS entry:

NAME: BBS Name (alternative names, as with groups, should be allowed since some boards renamed themselves over time)

LOCATION: Use the same location engine as with individual sceners. I am very much against having a field with telephone numbers, because even if a board was 100% leagl, this still could be unpleasant for the former sysop (or annoying for the poor people who own the number now).

STAFF: This could be done in the manner of prod credits, but with following pulldown roles "Sysop", "Co-Sysop". 

AFFILS: Also like prod credits, but with groups, not sceners, to enter. Following pulldown roles: "WHQ", "HQ", "Memberboard", "Distsite"

BBS INTROS: Possibility to link prods, like invitros are linked to parties.

TEXT ADS: Possibility to upload textmode BBS ads and probably display them with Ansilove.

This is just a suggestion, of course, and I am no coder, but this is not that hard to achieve, is it? And the value to scene history preservation would be immense.

**Comment by glennlunder** [comment]
I would say Staff should be handled more in the same way as groups, since in some instances staff came and left, and boards changed hands, even. Therefore a "former sysop" status would be appropriate.

Also, I am sure we could talk to @Gargaj about a dump of the board info from Pouët to get us started, and so @dipswitch- wouldn't have to duplicate more effort than necessary.

Obviously, there would need to be a trivia field.

For years, I've been adding "Promotes the bbs'es" strings to cracktros and the like - it would obviously be great to integrate that in a seamless way as well, if we go ahead and implement this in the future.

Finally, dial-up bbs'es began being replaced/fusioned into telnet bbs'es and ftp sites in the late 90s - along with the emergence of the early console scene, it was prevalent with a mix of bbs'es of both types and ftp sites. Hence, it would make sense to include ftp sites as well.

**Comment by glennlunder** [comment]
With the amount of bbs dump digging I'm doing these days, and all the neat/cool/interesting info that surfaces, I'm bumping this up a level to the mid tier of importantness (is that a word?).

I constantly feel like there is lots of info that I have no place to "park". A couple of observations;

I would like tagging enabled, for things like the bbs system the board used.

I think we could actually safely store bbs numbers (as opposed to what @dipswitch- said above), if we store them in a way that not everyone can see them, and we could match on searches, for example. This would actually be super useful for older intros that just list numbers and so forth.

**Comment by Gargaj** [comment]
I know this isn't necessary my call but is it a good idea to have even more data duplicated between Pouet and Demozoo? It's just twice the maintenance.

**Comment by glennlunder** [comment]
Based on a suggestion by Ipggi on Slack, I've created a shared Google Sheet for adding some rudimentary bits of information to give us an idea of what info we're conceivable going to need fields for.

https://docs.google.com/spreadsheets/d/16Lk6zm_c3egscXZ4IwcdYWzyi8ylq5B-sIV56s1F9t0/edit?usp=sharing
