### ISSUE TITLE
Embedded video

### ISSUE THREAD

**Issue by glennlunder** [demozoo/demozoo#50]
Video more tightly embedded in the browsing experience, right in along with the screenshots. Support is planned for YouTube, Vimeo, Capped.tv, Demoscene.tv and dhs.tv.

**Comment by gasman** [comment]
Youtube + Vimeo implemented as of 50c07dc10299d4de85c4bef268dcc0321129d98b

**Comment by gasman** [comment]
I'm counting this as done now. Youtube and Vimeo cover most bases - the others are trickier, because they either don't provide a screenshot that we can extract and use as the background image for the 'play' button, or only support embedding via Flash (just say no, kids). Anyone who feels strongly about support for them can open a new ticket about it :-)
