### ISSUE TITLE
Make MS-DOS encoding default for nfo/bbs-txt upload

### ISSUE THREAD

**Issue by dipswitch-** [demozoo/demozoo#525]
99% of the uploaded textfiles stem from the DOS era. So it would make much more sense to make MS-DOS (CP437) the default encoding when uploading a textfile, instead of Western (Iso-8859-1). I upload dozens of txtfiles almost daily, and the manual switching of encoding to MS-DOS is a rather annoying additional work step to make.

**Comment by bengarrett** [comment]
I feel the same and many texts are uploaded but get left with the incorrect encoding. 

Unfortunately, I don't know Python, so I cannot do a PR. But looking at [TestFile in models.py](https://github.com/demozoo/demozoo/blob/main/demoscene/models.py#L713), there's a [guess_encoding method](https://github.com/demozoo/demozoo/blob/main/demoscene/models.py#L739) that could be expanded? Currently, if the `fuzzy` arg is true, it tests for an ANSI escape code `\x1b[`, otherwise defaults to Windows-1252 or ISO-8859-1.

```py
    def guess_encoding(data, fuzzy=False):
        """
        Make a best guess at what character encoding this data is in.
        Returns a tuple of (encoding, decoded_data).
        If fuzzy=False, we return None if the encoding is uncertain;
        if fuzzy=True, we make a wild guess.
        """
        # Try to decode the data using several candidate encodings, least permissive first.
        # Accept the first one that doesn't break.
        if fuzzy:
            if b'\x1b[' in data:
                # data contains ANSI escape codes, so is probably a DOS ANSI with cp437 encoding
                candidate_encodings = ['ascii', 'utf-8', 'cp437', 'windows-1252', 'iso-8859-1']
            else:
                candidate_encodings = ['ascii', 'utf-8', 'windows-1252', 'iso-8859-1']
        else:
            candidate_encodings = ['ascii', 'utf-8']
```

Could the if statement be enhanced to also look for characters that match values `B0` (176) through to `DF` (223)? These are all the distinctive CP437 block, line, and shade characters.

![Screenshot from 2023-01-07 15-52-42](https://user-images.githubusercontent.com/513842/211131716-dd0e9633-0aee-4959-82d9-6cd59182f675.png)

While these values in ISO-8859-1 and Win-1252 match various extended-Latin characters. 

![Screenshot from 2023-01-07 15-53-01](https://user-images.githubusercontent.com/513842/211131761-8b07cb60-578a-4368-8928-519cf2037043.png)

For BBSes and pages of art packs etc from the 1980s or 1990s, _Text ads_ and _Info file_ uploads that flag a match would suggest the text is most likely CP437 encoded?

**Comment by gasman** [comment]
@bengarrett Looking for characters in that range is effectively what the code is doing already - the `candidate_encodings` list is a list of encodings for it to try in sequence, so if it's able to read the entire file as 7-bit ASCII (the first encoding in the list) then it can stop immediately, and the question of detecting the encoding doesn't arise at all. The problem is that when there _are_ bytes above `0x80`, there really is no reliable way to know which 8-bit encoding is used - for example, a results.txt file from a Russian demoparty written in Cyrillic text is likely to also have long strings of bytes in the B0-DF range.

The only real way forward is to provide `guess_encoding` with the extra context of where the file came from (i.e. "this is an ad for a 1990s BBS, so it's probably CP437"), as @dipswitch- suggests.

**Comment by bengarrett** [comment]
@gasman That extra context to provide saner defaults would be really helpful! Currently, CP437 is not detected for texts other than ANSI files?

But, with texts uploaded as TEXT ADS to the BBSes. One could assume the uploads containing `0x80`+ high characters are more often either ISO 8859-1 or CP437.

A broad assumption but if there are characters between `0xA0`-`0xBF`, then it's more likely Amiga 8859-1 art, and between `0xC0`-`0xDF` then CP437 art. With the proliferation of MS-DOS BBSes, advertising, and art, the guess may be wrong at times, but it is preferable to CP437 never being used as the default encoding?

And the same for INFO FILES uploads for 1980-90s ANSI art packs etc. most of which came out of the North American PC scene.

😢 ![Screenshot from 2023-01-08 14-30-10](https://user-images.githubusercontent.com/513842/211179260-0944c86a-031f-44c2-992f-39ce5ff104c8.png)
