### ISSUE TITLE
Feature request: Mastodon link recognition

### ISSUE THREAD

**Issue by Paul-JanPauptit** [demozoo/demozoo#544]
A non-trivial amount of demosceners has opened up a Mastadon account now that the future of twitter is unsure.

I'm trying to give some demoparties a presence at this platform (flailing about like usual) but demozoo represents/stores those links as a general WWW link.  Dedicated support would be nice, but I realize recognizing Mastodon instances from a barebones hyperlink is a non-trivial task. Judging by the Twitter->Mastodon migration tools that popped up over the last couple of weeks, this problem is kinda sorta solved by others already.

**Comment by gasman** [comment]
I think the Twitter->Mastodon migration tools just look for a `@username@example.com` string in the username or bio, so they're solving an easier version of the problem...

Presumably there's some API endpoint or header/meta tag that we can poke to find out if a host is a Mastodon instance, in which case the best strategy for this is probably something like:

* have a scheduled task running every week or so that looks for external links with an `@` character in the path portion, and tests that hostname to see if it's a Mastodon instance
* store the ones we find in a database table (and make that available for admins to tweak, in case there are edge cases that can't be automated)
* come up with a definition for Mastodon accounts within the [groklinks](https://github.com/demozoo/demozoo/blob/main/demoscene/utils/groklinks.py) module, that works more or less like the other sites, but rather than having a hard-coded list of allowed hostnames, pull it from that database table (and cache it for an hour or so, so that we're not constantly hitting the database)

**Comment by Paul-JanPauptit** [comment]
Oh, sorry if I was being unclear, as part of the initial authentication flow most migration tools offer you a "select mastadon instance to authenticate with" screen. E.g. see the source of https://github.com/pruvisto/debirdify , where they pull the base list of instances from the API at https://instances.social . 

That list is very unlikely to be complete, so depending on _how_ complete it is your suggestion of crawling is either a _fair bit_ or a _whole lot_ better. 😄

**Comment by gasman** [comment]
I asked ChatGPT how to recognise whether a website is a Mastodon instance, and it suggested checking for the URL `/api/v1/instance`, which is genuinely the first time it's provided me with a more helpful answer than a Google search...

After all that, though, a quick check of the database revealed that there are currently 14 Mastodon account links in the database across 9 different instances, so for now I've just hard-coded those 9. If we ever reach the point that managing that list manually is unsustainable _then_ we can consider building a fancy polling mechanism to discover Mastodon instances, but right now that would be massive over-engineering. :-)

**Comment by Paul-JanPauptit** [comment]
Ha, that’s amazing! :-)

 

Great analysis, totally agree with the “no over-engineering” argument, check!

At some point we might need to think about gently pushing people towards leaving more of their social links on demozoo, I’ve recently hand-compared e.g. the insta following of revision v.s. their demozoo insta links, and demozoo is just barren. But that’s only from the viewpoint of wanting to build strong demoscene networks on every social platform, maybe not in everyone’s best interest, and definitely off topic for this thread. Thank you (and ChatGPT) for picking this up!
