### ISSUE TITLE
Canonical YouTube urls should allow time offset

### ISSUE THREAD

**Issue by glennlunder** [demozoo/demozoo#94]
Saga: While it's nice that Demozoo tries to make URLs canonical, it would be even nicer if not only the v= parameter could be preserved but also t= time offset, e.g.  http://www.youtube.com/watch?v=SRfo02bkI_Q&t=441
That would be useful like this example live footage that includes several compo entries in one video.

**Comment by tomaes** [comment]
Mhmm, isn't this just an issue with URLs like:
http://www.youtube.com/watch?v=978WIztBYO4?t=16322

Youtube will ignore everything after the second question mark and start the video at the very beginning.

URLs like this one work just fine, but they are currently transformed to the format above:
https://youtu.be/978WIztBYO4?t=14810

(not sure, if this will get lost here, or if this should be a new 'issue')

**Comment by gasman** [comment]
@tomaes What you've found there is a bug, which _almost_ (but not quite) works around the issue @glennlunder reported here :-)

Internally we store Youtube links as just the ID (`978WIztBYO4`), which is more useful than the full URL (because we can use it for embedding the video, as well as being able to identify duplicates regardless of how they were originally entered). The bug is that our link parser will look at a URL like https://youtu.be/978WIztBYO4?t=14810 and decide that the ID is `978WIztBYO4?t=14810`. This isn't a valid Youtube video ID, but if you insert that string into the long-form URL you (coincidentally) get something that almost looks like a valid link with a timestamp.

So, there's a two-part fix here:

* (the bugfix) Fix the parser of youtu.be shortcut links so that the ?t=14180 isn't counted as part of the ID
* (the feature request) Recognise the timestamp parameter as a real thing, and store it as part of the link record in a way that the rest of the code (e.g. video embedding) knows how to handle.

**Comment by DannyCork** [comment]
Just noticed this issue also. I added links to youtube videos from DemoBit. The video is hours long so I linked to the timeoffset but it gets stripped e.g. : https://demozoo.org/productions/167689/
